# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=tuple)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('userPwd', models.CharField(max_length=100)),
                ('userPhone', models.CharField(default='', max_length=30)),
                ('userStatus', models.IntegerField(default=0, max_length=2)),
            ],
        ),
    ]
